version: "2"

volumes:
  postgres_data_local: {}

services:
  app:
    image: omar/timetrex:dev
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./docker/timetrex:/var/www/html/timetrex:rw
      - ./docker-entrypoint.sh:/docker-entrypoint.sh:rw
  database:
    image: postgres:10 # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose